List categories = [
  "Tech",
  "Data Science",
  "Web Development",
  "Machine Learning",
  "Science",
  "Math",
  "Arts",
  "Productivity",
  "Carrier",
  "Food",
  "Travel",
  "Health" "Movie",
  "Political",
  "Business",
  "Sports",
  "News",
  "Personal",
];
